add_test([=[formats.format]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=formats.format]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[formats.format]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[graph.src_vertex]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=graph.src_vertex]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[graph.src_vertex]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[graph.graph_load]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=graph.graph_load]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[graph.graph_load]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[graph.graph]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=graph.graph]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[graph.graph]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[memory.memory]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=memory.memory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[memory.memory]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[framework.problem]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=framework.problem]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[framework.problem]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[operators.prallel_for]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=operators.prallel_for]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[operators.prallel_for]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[operators_advance.merge_path_search]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=operators_advance.merge_path_search]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[operators_advance.merge_path_search]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[operators_advance.merge_path_load_balance_partitions]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=operators_advance.merge_path_load_balance_partitions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[operators_advance.merge_path_load_balance_partitions]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[operators_advance.merge_path_advance_basic]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=operators_advance.merge_path_advance_basic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[operators_advance.merge_path_advance_basic]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[operators_advance.merge_path_runtime_dispatch]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=operators_advance.merge_path_runtime_dispatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[operators_advance.merge_path_runtime_dispatch]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[utils.type_limits]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=utils.type_limits]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[utils.type_limits]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[cuda.launch_box_occupancy]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=cuda.launch_box_occupancy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[cuda.launch_box_occupancy]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[cuda.launch_box_fallback]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=cuda.launch_box_fallback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[cuda.launch_box_fallback]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[cuda.launch_box_define]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=cuda.launch_box_define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[cuda.launch_box_define]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[cuda.context]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=cuda.context]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[cuda.context]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[cuda.device_properties]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=cuda.device_properties]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[cuda.device_properties]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[containers.array]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=containers.array]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[containers.array]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[io.smtx]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=io.smtx]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[io.smtx]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algorithm.tc]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=algorithm.tc]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algorithm.tc]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[algorithm.tc_self_loop_vertex]=]  /home/muhosama/gunrock/build_amd/bin/unittests [==[--gtest_filter=algorithm.tc_self_loop_vertex]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[algorithm.tc_self_loop_vertex]=]  PROPERTIES WORKING_DIRECTORY /home/muhosama/gunrock/build_amd/unittests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  unittests_TESTS formats.format graph.src_vertex graph.graph_load graph.graph memory.memory framework.problem operators.prallel_for operators_advance.merge_path_search operators_advance.merge_path_load_balance_partitions operators_advance.merge_path_advance_basic operators_advance.merge_path_runtime_dispatch utils.type_limits cuda.launch_box_occupancy cuda.launch_box_fallback cuda.launch_box_define cuda.context cuda.device_properties containers.array io.smtx algorithm.tc algorithm.tc_self_loop_vertex)
