var hierarchy =
[
    [ "gunrock::experimental::frontier::boolmap_frontier_t< type_t >", "classgunrock_1_1experimental_1_1frontier_1_1boolmap__frontier__t.html", null ],
    [ "gunrock::operators::advance::merge_path_v2::coordinate_t< index_t >", "structgunrock_1_1operators_1_1advance_1_1merge__path__v2_1_1coordinate__t.html", null ],
    [ "gunrock::geo::coordinates_t", "structgunrock_1_1geo_1_1coordinates__t.html", null ],
    [ "gunrock::graph::edge_pair_t< edge_t >", "structgunrock_1_1graph_1_1edge__pair__t.html", null ],
    [ "gunrock::graph::empty_coo_t", "structgunrock_1_1graph_1_1empty__coo__t.html", null ],
    [ "gunrock::graph::empty_csc_t", "structgunrock_1_1graph_1_1empty__csc__t.html", null ],
    [ "gunrock::graph::empty_csr_t", "structgunrock_1_1graph_1_1empty__csr__t.html", null ],
    [ "gunrock::graph::empty_graph_t", "structgunrock_1_1graph_1_1empty__graph__t.html", null ],
    [ "enactor_t", null, [
      [ "gunrock::bc::enactor_t< problem_t >", "structgunrock_1_1bc_1_1enactor__t.html", null ],
      [ "gunrock::bfs::enactor_t< problem_t >", "structgunrock_1_1bfs_1_1enactor__t.html", null ],
      [ "gunrock::color::enactor_t< problem_t >", "structgunrock_1_1color_1_1enactor__t.html", null ],
      [ "gunrock::geo::enactor_t< problem_t >", "structgunrock_1_1geo_1_1enactor__t.html", null ],
      [ "gunrock::hits::enactor_t< problem_t >", "structgunrock_1_1hits_1_1enactor__t.html", null ],
      [ "gunrock::kcore::enactor_t< problem_t >", "structgunrock_1_1kcore_1_1enactor__t.html", null ],
      [ "gunrock::mst::enactor_t< problem_t >", "structgunrock_1_1mst_1_1enactor__t.html", null ],
      [ "gunrock::ppr::enactor_t< problem_t >", "structgunrock_1_1ppr_1_1enactor__t.html", null ],
      [ "gunrock::pr::enactor_t< problem_t >", "structgunrock_1_1pr_1_1enactor__t.html", null ],
      [ "gunrock::spgemm::enactor_t< problem_t >", "structgunrock_1_1spgemm_1_1enactor__t.html", null ],
      [ "gunrock::spmv::enactor_t< problem_t >", "structgunrock_1_1spmv_1_1enactor__t.html", null ],
      [ "gunrock::sssp::enactor_t< problem_t >", "structgunrock_1_1sssp_1_1enactor__t.html", null ]
    ] ],
    [ "gunrock::experimental::async::enactor_t< algorithm_problem_t >", "structgunrock_1_1experimental_1_1async_1_1enactor__t.html", null ],
    [ "gunrock::experimental::async::enactor_t< problem_t >", "structgunrock_1_1experimental_1_1async_1_1enactor__t.html", [
      [ "gunrock::experimental::async::bfs::enactor_t< problem_t >", "structgunrock_1_1experimental_1_1async_1_1bfs_1_1enactor__t.html", null ]
    ] ],
    [ "gunrock::graph::graph_coo_t< vertex_t, edge_t, weight_t >", "classgunrock_1_1graph_1_1graph__coo__t.html", null ],
    [ "gunrock::graph::graph_csc_t< vertex_t, edge_t, weight_t >", "classgunrock_1_1graph_1_1graph__csc__t.html", null ],
    [ "gunrock::graph::graph_csr_t< vertex_t, edge_t, weight_t >", "classgunrock_1_1graph_1_1graph__csr__t.html", null ],
    [ "gunrock::graph::graph_properties_t", "structgunrock_1_1graph_1_1graph__properties__t.html", null ],
    [ "gunrock::hits::problem_t< graph_t >::op< T >", "structgunrock_1_1hits_1_1problem__t_1_1op.html", null ],
    [ "gunrock::hits::param_c", "classgunrock_1_1hits_1_1param__c.html", null ],
    [ "gunrock::color::param_t", "structgunrock_1_1color_1_1param__t.html", null ],
    [ "gunrock::sssp::param_t< vertex_t >", "structgunrock_1_1sssp_1_1param__t.html", null ],
    [ "gunrock::mst::param_t< vertex_t >", "structgunrock_1_1mst_1_1param__t.html", null ],
    [ "gunrock::experimental::async::bfs::param_t< vertex_t >", "structgunrock_1_1experimental_1_1async_1_1bfs_1_1param__t.html", null ],
    [ "gunrock::ppr::param_t< vertex_t, weight_t >", "structgunrock_1_1ppr_1_1param__t.html", null ],
    [ "gunrock::bfs::param_t< vertex_t >", "structgunrock_1_1bfs_1_1param__t.html", null ],
    [ "gunrock::pr::param_t< weight_t >", "structgunrock_1_1pr_1_1param__t.html", null ],
    [ "gunrock::spgemm::param_t< graph_t >", "structgunrock_1_1spgemm_1_1param__t.html", null ],
    [ "gunrock::spmv::param_t< weight_t >", "structgunrock_1_1spmv_1_1param__t.html", null ],
    [ "gunrock::geo::param_t", "structgunrock_1_1geo_1_1param__t.html", null ],
    [ "gunrock::bc::param_t< vertex_t >", "structgunrock_1_1bc_1_1param__t.html", null ],
    [ "gunrock::problem_t< graph_t >", "structgunrock_1_1problem__t.html", [
      [ "gunrock::bc::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1bc_1_1problem__t.html", null ],
      [ "gunrock::bfs::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1bfs_1_1problem__t.html", null ],
      [ "gunrock::color::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1color_1_1problem__t.html", null ],
      [ "gunrock::experimental::async::bfs::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1experimental_1_1async_1_1bfs_1_1problem__t.html", null ],
      [ "gunrock::geo::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1geo_1_1problem__t.html", null ],
      [ "gunrock::hits::problem_t< graph_t >", "structgunrock_1_1hits_1_1problem__t.html", null ],
      [ "gunrock::kcore::problem_t< graph_t, result_type >", "structgunrock_1_1kcore_1_1problem__t.html", null ],
      [ "gunrock::mst::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1mst_1_1problem__t.html", null ],
      [ "gunrock::ppr::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1ppr_1_1problem__t.html", null ],
      [ "gunrock::pr::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1pr_1_1problem__t.html", null ],
      [ "gunrock::spgemm::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1spgemm_1_1problem__t.html", null ],
      [ "gunrock::spmv::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1spmv_1_1problem__t.html", null ],
      [ "gunrock::sssp::problem_t< graph_t, param_type, result_type >", "structgunrock_1_1sssp_1_1problem__t.html", null ]
    ] ],
    [ "gunrock::hits::result_c< graph_t >", "classgunrock_1_1hits_1_1result__c.html", null ],
    [ "gunrock::spgemm::result_t< csr_t >", "structgunrock_1_1spgemm_1_1result__t.html", null ],
    [ "gunrock::experimental::async::bfs::result_t< edge_t >", "structgunrock_1_1experimental_1_1async_1_1bfs_1_1result__t.html", null ],
    [ "gunrock::bc::result_t< weight_t >", "structgunrock_1_1bc_1_1result__t.html", null ],
    [ "gunrock::ppr::result_t< weight_t >", "structgunrock_1_1ppr_1_1result__t.html", null ],
    [ "gunrock::color::result_t< vertex_t >", "structgunrock_1_1color_1_1result__t.html", null ],
    [ "gunrock::pr::result_t< weight_t >", "structgunrock_1_1pr_1_1result__t.html", null ],
    [ "gunrock::spmv::result_t< weight_t >", "structgunrock_1_1spmv_1_1result__t.html", null ],
    [ "gunrock::bfs::result_t< vertex_t >", "structgunrock_1_1bfs_1_1result__t.html", null ],
    [ "gunrock::mst::result_t< vertex_t, weight_t >", "structgunrock_1_1mst_1_1result__t.html", null ],
    [ "gunrock::sssp::result_t< vertex_t, weight_t >", "structgunrock_1_1sssp_1_1result__t.html", null ],
    [ "gunrock::geo::result_t", "structgunrock_1_1geo_1_1result__t.html", null ],
    [ "gunrock::kcore::result_t< vertex_t >", "structgunrock_1_1kcore_1_1result__t.html", null ],
    [ "gunrock::frontier::vector_frontier_t< vertex_t, edge_t, _kind >", "classgunrock_1_1frontier_1_1vector__frontier__t.html", [
      [ "gunrock::frontier::frontier_t< vertex_t, edge_t, _kind, _view >", "classgunrock_1_1frontier_1_1frontier__t.html", null ]
    ] ],
    [ "gunrock::graph::vertex_pair_t< vertex_t >", "structgunrock_1_1graph_1_1vertex__pair__t.html", null ],
    [ "graph_view_t", null, [
      [ "gunrock::graph::graph_t< space, vertex_t, edge_t, weight_t, graph_view_t >", "classgunrock_1_1graph_1_1graph__t.html", null ]
    ] ]
];