./bin/bfs -m ~/suitesparse/IBM_EDA/dc2/dc2.mtx --collect_metrics --json_dir=./bfs --json_file=dc2.json --num_runs=1 
./bin/bfs -m ~/suitesparse/Freescale/circuit5M/circuit5M.mtx --collect_metrics --json_dir=./bfs --json_file=circuit5M.json --num_runs=1
./bin/bfs -m ~/suitesparse/LAW/in-2004/in-2004.mtx --collect_metrics --json_dir=./bfs --json_file=in-2004.json --num_runs=1
./bin/bfs -m ~/suitesparse/Freescale/transient/transient.mtx --collect_metrics --json_dir=./bfs --json_file=transient.json --num_runs=1
./bin/bfs -m ~/suitesparse/GHS_indef/boyd2/boyd2.mtx --collect_metrics --json_dir=./bfs --json_file=boyd2.json --num_runs=1
./bin/bfs -m ~/suitesparse/Andrianov/ins2/ins2.mtx --collect_metrics --json_dir=./bfs --json_file=ins2.json --num_runs=1
./bin/bfs -m ~/suitesparse/Williams/webbase-1M/webbase-1M.mtx --collect_metrics --json_dir=./bfs --json_file=Webbase.json --num_runs=1 
./bin/bfs -m ~/suitesparse/Sandia/ASIC_680k/ASIC_680k.mtx --collect_metrics --json_dir=./bfs --json_file=ASIC_680k.json --num_runs=1
./bin/bfs -m ~/suitesparse/Williams/pdb1HYS/pdb1HYS.mtx --collect_metrics --json_dir=./bfs --json_file=Protein.json --num_runs=1 
./bin/bfs -m ~/suitesparse/Williams/cant/cant.mtx --collect_metrics --json_dir=./bfs --json_file=Cantilever.json --num_runs=1
./bin/bfs -m ~/suitesparse/Williams/consph/consph.mtx --collect_metrics --json_dir=./bfs --json_file=Spheres.json --num_runs=1
./bin/bfs -m ~/suitesparse/Andrianov/mip1/mip1.mtx --collect_metrics --json_dir=./bfs --json_file=mip1.json --num_runs=1
./bin/bfs -m ~/suitesparse/GHS_psdef/crankseg_2/crankseg_2.mtx --collect_metrics --json_dir=./bfs --json_file=crankseg_2.json --num_runs=1
./bin/bfs -m ~/suitesparse/PARSEC/Si41Ge41H72/Si41Ge41H72.mtx --collect_metrics --json_dir=./bfs --json_file=Si41Ge41H72.json --num_runs=1
./bin/bfs -m ~/suitesparse/PARSEC/Ga41As41H72/Ga41As41H72.mtx --collect_metrics --json_dir=./bfs --json_file=Ga41As41H72.json --num_runs=1
./bin/bfs -m ~/suitesparse/LAW/eu-2005/eu-2005.mtx --collect_metrics --json_dir=./bfs --json_file=eu-2005.json --num_runs=1
./bin/bfs -m ~/suitesparse/Rajat/rajat31/rajat31.mtx --collect_metrics --json_dir=./bfs --json_file=rajat31.json --num_runs=1
./bin/bfs -m ~/suitesparse/GHS_psdef/ldoor/ldoor.mtx --collect_metrics --json_dir=./bfs --json_file=ldoor.json --num_runs=1
./bin/bfs -m ~/suitesparse/Oberwolfach/bone010/bone010.mtx --collect_metrics --json_dir=./bfs --json_file=bone010.json --num_runs=1